//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoReservation.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunden
    {
        public Kunden()
        {
            this.Reservations = new HashSet<Reservationen>();
        }
    
        public int Id { get; set; }
        public string Nachname { get; set; }
        public string Vorname { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
    
        public virtual ICollection<Reservationen> Reservations { get; set; }
    }
}
